app/controllers/api_controller.rb
app/controllers/home_controller.rb
app/javascript/models/api.js
app/javascript/packs/application.js
app/javascript/pages/search.js
app/models/assessment.rb
app/models/question.rb
app/models/user.rb
app/models/user/anonymous.rb
app/serializers/api/v1/question_serializer.rb
app/views/home/application.html.erb
config/secrets.yml
db/migrate/20180321160325_create_questions.rb
db/schema.rb
lib/a15k/interactions.rb
lib/a15k/metadata.rb
spec/clients/ruby_spec.rb
spec/controllers/home_controller_spec.rb
spec/factories/assessments.rb
spec/factories/formats.rb
spec/factories/questions.rb
spec/javascript/factories/index.js
spec/javascript/models/assessment.spec.js
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/search.spec.js
spec/models/question_spec.rb
spec/models/user_spec.rb
spec/requests/assessments_spec.rb

But only allow power users access to tokens and user management

Allow non-power users to access user interface

---

.gitignore
.travis.yml
app/controllers/api/v1/users_controller.rb
app/javascript/components/surety-guard.js
app/javascript/models/api.js
app/javascript/models/user.js
app/javascript/packs/application.js
app/javascript/pages/home.js
app/javascript/pages/users.js
app/javascript/pages/users/row.js
app/models/format.rb
app/models/member.rb
app/models/user.rb
spec/javascript/components/__snapshots__/surety-guard.spec.js.snap
spec/javascript/components/surety-guard.spec.js
spec/javascript/pages/__snapshots__/home.spec.js.snap
spec/javascript/pages/__snapshots__/users.spec.js.snap
spec/javascript/pages/home.spec.js
spec/javascript/pages/users.spec.js
spec/models/member_spec.rb
spec/models/user_spec.rb
spec/requests/users_spec.rb
yarn.lock

* Requires confirmation before unlinking user
* Displays a "not a member" message for users who do not belong to a member
* Hides delete button from last power user in a membership
* Redirects to "not a member" message after a self deletion
* Redirect to home page after a self demotion since user can no longer manage accounts

User unlinking and roles

---

app/javascript/pages/search.js
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/search.spec.js

add search help

---

app/javascript/packs/application.js

replace home link with "Assessment Network" title

---

Gemfile.lock
app/javascript/models/config.js
app/javascript/packs/application.js
app/views/home/application.html.erb
spec/javascript/packs/__snapshots__/application.spec.js.snap
spec/javascript/packs/application.spec.js
yarn.lock

And change it's title to be the username/name

Split menu into actions and user

---

app/javascript/components/button.js
app/javascript/components/section-heading.js
app/javascript/models/api.js
app/javascript/models/model-collection.js
app/javascript/packs/application.js
app/javascript/pages/api.js
app/javascript/pages/index.js
app/javascript/pages/interactions.js
app/javascript/pages/interactions/edit.js
app/javascript/pages/tokens.js
app/javascript/pages/users.js
spec/javascript/packs/__snapshots__/application.spec.js.snap
spec/javascript/pages/__snapshots__/api.spec.js.snap
spec/javascript/pages/__snapshots__/users.spec.js.snap
spec/javascript/pages/api.spec.js
spec/javascript/pages/tokens/__snapshots__/edit.spec.js.snap

Combined api page

---

app/javascript/models/interaction-app.js

display "coming soon" for interactions while widget is being developed

---

app/controllers/api/v1/access_tokens_controller.rb
app/javascript/components/buttons-bar.js
app/javascript/components/surety-guard.js
app/javascript/helpers/react.js
app/javascript/models/access-token.js
app/javascript/models/api.js
app/javascript/pages/tokens/editing.js
app/models/access_token.rb
app/models/user.rb
app/serializers/api/v1/access_token_serializer.rb
db/migrate/20180516193738_create_access_tokens.rb
package.json
spec/clients/kitchen-sink_spec.rb
spec/clients/ruby_spec.rb
spec/controllers/api_controller_spec.rb
spec/javascript/components/__snapshots__/surety-guard.spec.js.snap
spec/javascript/packs/__snapshots__/application.spec.js.snap
spec/javascript/pages/__snapshots__/api.spec.js.snap
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/__snapshots__/users.spec.js.snap
spec/javascript/pages/tokens/__snapshots__/edit.spec.js.snap
spec/javascript/pages/tokens/edit.spec.js
spec/javascript/spec_helper.js
spec/requests/access_tokens_spec.rb
spec/requests/assessments_spec.rb
spec/requests/formats_spec.rb
spec/requests/interactions_spec.rb
spec/requests/users_spec.rb
yarn.lock

Also makes tokens non-expirable so they don't change on every load.

Delete tokens instead of using `is_revoked` flag

---

app/views/home/application.html.erb
spec/helpers/signin_helpers.rb
spec/requests/application_spec.rb
spec/spec_helper.rb

This snuck in and wasn't caught because we weren't testing actually rendering the html

Render html page even if member is nil

---

app/javascript/components/copy-on-focus-input.js
app/javascript/helpers/clipboard.js
app/javascript/packs/application.js
app/javascript/pages/interactions/edit.js
app/javascript/pages/interactions/listing.js
lib/a15k/interactions/fake_api.rb
spec/javascript/components/copy-on-focus-input.spec.js

fixes for:
* Adds member name and user role to menu
* Adds inputs for obtaining the interactions id and token,
*  Fixes adding a interactions app when stubbed

Updates from aug 8 review

---

lib/demo/member_b.rb
lib/demo/member_b_fitb.html.erb
lib/demo/member_b_mc.html.erb
lib/demo/member_b_short.html.erb
lib/tasks/demo2.rake
spec/lib/demo2_spec.rb

Adds another member to Demo 2.  This member uses an XML format instead of JSON.  The preview_html also uses a different font.  (we will need to figure out how to isolate CSS from different)

member B of demo 2

---

app/javascript/models/assessment.js
app/javascript/models/question.js
app/javascript/models/solution.js
app/javascript/packs/application.js
app/javascript/pages/formats.js
app/javascript/pages/search.js
app/javascript/pages/search/preview.js
package.json
spec/javascript/packs/__snapshots__/application.spec.js.snap
yarn.lock

Add link to format from search preview

---

app/javascript/pages/formats.js
app/javascript/pages/search.js
spec/javascript/pages/__snapshots__/formats.spec.js.snap
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/formats.spec.js
spec/javascript/pages/search.spec.js

Formats test fixes

---

.travis.yml
app/controllers/api/v1/assessments_controller.rb
app/javascript/models/assessment.js
app/javascript/models/format.js
app/javascript/models/member.js
app/javascript/pages/search/preview.js
app/serializers/api/serializer.rb
app/serializers/api/v1/assessment_serializer.rb
app/serializers/api/v1/member_serializer.rb
bin/travis-preflight
package.json
spec/javascript/pages/__snapshots__/search.spec.js.snap
yarn.lock

add download button and additional info to the search preview

---

app/controllers/assessment_controller.rb
app/helpers/assessment_helper.rb
app/javascript/packs/preview.js
app/javascript/pages/search/preview.js
app/views/assessment/preview.html.erb
config/routes.rb
package.json
spec/controllers/assessment_controller_spec.rb
spec/factories/assessments.rb
spec/helpers/assessment_helper_spec.rb
spec/javascript/pages/__snapshots__/search.spec.js.snap
yarn.lock

the only UI change is the download button can no longer float to the right since the iframe content can't be wrapped around it.

display assessment previews in an iframe

---

app/javascript/models/assessment.js
app/javascript/models/variant.js
app/javascript/pages/search/preview.js
lib/a15k/metadata/fake_api.rb
spec/javascript/factories/index.js
spec/javascript/pages/__snapshots__/search.spec.js.snap

Changes JS code to come into alignment with recent backend name changes.

change question to variant in JS

---

app/javascript/models/assessment.js
app/javascript/models/assessment/preview.js
app/javascript/models/variant.js
app/javascript/packs/application.js
app/javascript/pages/search/preview.js
app/views/home/application.html.erb
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/search.spec.js

set iframe contents using srcdoc

---

app/javascript/pages/search/preview.js

JP's version of wrapping tags

---

app/controllers/api/v1/assessments_controller.rb
app/controllers/api_controller.rb
app/javascript/models/api.js
app/javascript/models/assessment.js
app/javascript/pages/search.js
app/javascript/pages/search/collection.js
app/javascript/pages/search/pagination.js
app/javascript/pages/search/results.js
app/models/assessment.rb
lib/a15k/metadata.rb
lib/a15k/metadata/api.rb
lib/a15k/metadata/fake_api.rb
lib/a15k/metadata/query_result.rb
package.json
spec/javascript/pages/__snapshots__/search.spec.js.snap
spec/javascript/pages/search.spec.js
spec/lib/a15k/metadata_spec.rb
spec/requests/assessments_spec.rb
yarn.lock

Paginate search results

---

lib/a15k/metadata/api.rb
lib/a15k/metadata/json_api.rb

goes with https://github.com/a15k/metadata-repository/pull/8

support pagination on metadata requests

---

app/javascript/pages/interactions/edit.js
spec/javascript/pages/interactions/__snapshots__/edit.spec.js.snap
spec/javascript/pages/interactions/edit.spec.js

display correct api_id instead of app.id
